apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
images:
  - name: ceerat-user-service
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-user-service
    newTag: latest
