apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespaces.yaml
  - base/shared-config.yaml
  - base/ceerat-user-service/deployment.yaml
  - base/ceerat-user-service/service.yaml
  - base/ceerat-user-service/network-policy.yaml
  - base/ceerat-agent-service/deployment.yaml
  - base/ceerat-agent-service/service.yaml
  - base/frontend-apps/deployments.yaml
  - base/frontend-apps/services.yaml
  - base/ingress/ingress.yaml
  - base/cloud-sql-proxy/secret.yaml
  - base/cloud-sql-proxy/service-account.yaml
  - base/cloud-sql-proxy/deployment.yaml
  - base/cloud-sql-proxy/service.yaml
  - base/typesense/secret.yaml
  - base/typesense/statefulset.yaml
  - base/typesense/service.yaml
images:
  - name: ceerat-user-service
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-user-service
    newTag: latest
  - name: ceerat-agent-service
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-agent-service
    newTag: latest
  - name: ceerat-web-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-web-ui
    newTag: latest
  - name: ceerat-admin-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-admin-ui
    newTag: latest
  - name: ceerat-customer-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-customer-ui
    newTag: latest
