apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ceerat-agent-service
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-agent-service
    newTag: latest
