apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployments.yaml
  - services.yaml
images:
  - name: ceerat-web-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-web-ui
    newTag: latest
  - name: ceerat-admin-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-admin-ui
    newTag: latest
  - name: ceerat-customer-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-customer-ui
    newTag: latest
