apiVersion: v1
kind: Service
metadata:
  name: ceerat-web-ui
  namespace: ceerat-frontend
  labels:
    app.kubernetes.io/name: ceerat-web-ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ceerat-web-ui
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: ceerat-admin-ui
  namespace: ceerat-frontend
  labels:
    app.kubernetes.io/name: ceerat-admin-ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ceerat-admin-ui
  ports:
    - name: http
      port: 3010
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: ceerat-customer-ui
  namespace: ceerat-frontend
  labels:
    app.kubernetes.io/name: ceerat-customer-ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ceerat-customer-ui
  ports:
    - name: http
      port: 3005
      targetPort: http
