apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - shared-config.yaml
  - ceerat-user-service/deployment.yaml
  - ceerat-user-service/service.yaml
  - ceerat-user-service/network-policy.yaml
  - ceerat-user-service/typesense-secret.yaml
  - ceerat-agent-service/deployment.yaml
  - ceerat-agent-service/service.yaml
  - frontend-apps/deployments.yaml
  - frontend-apps/services.yaml
  - ingress/ingress.yaml
  - postgres/secret.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - typesense/secret.yaml
  - typesense/statefulset.yaml
  - typesense/service.yaml
images:
  - name: ceerat-services-repo
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-services-repo
    newTag: latest
  - name: ceerat-apps-repo
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-apps-repo
    newTag: latest
