apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - shared-config.yaml
  - ceerat-user-service/deployment.yaml
  - ceerat-user-service/service.yaml
  - ceerat-user-service/network-policy.yaml
  - ceerat-agent-service/deployment.yaml
  - ceerat-agent-service/service.yaml
  - frontend-apps/deployments.yaml
  - frontend-apps/services.yaml
  - ingress/ingress.yaml
  - cloud-sql-proxy/secret.yaml
  - cloud-sql-proxy/service-account.yaml
  - cloud-sql-proxy/deployment.yaml
  - cloud-sql-proxy/service.yaml
  - typesense/secret.yaml
  - typesense/statefulset.yaml
  - typesense/service.yaml
images:
  - name: ceerat-user-service
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-user-service
    newTag: latest
  - name: ceerat-agent-service
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-agent-service
    newTag: latest
  - name: ceerat-web-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-web-ui
    newTag: latest
  - name: ceerat-admin-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-admin-ui
    newTag: latest
  - name: ceerat-customer-ui
    newName: us-docker.pkg.dev/PROJECT_ID/ceerat/ceerat-customer-ui
    newTag: latest
